# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/petruha2001/projects/minishell

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/petruha2001/projects/minishell

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/petruha2001/projects/minishell/CMakeFiles /home/petruha2001/projects/minishell/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/petruha2001/projects/minishell/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named minishell

# Build rule for target.
minishell: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minishell
.PHONY : minishell

# fast build rule for target.
minishell/fast:
	$(MAKE) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/build
.PHONY : minishell/fast

src/cd_builtin.o: src/cd_builtin.c.o

.PHONY : src/cd_builtin.o

# target to build an object file
src/cd_builtin.c.o:
	$(MAKE) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cd_builtin.c.o
.PHONY : src/cd_builtin.c.o

src/cd_builtin.i: src/cd_builtin.c.i

.PHONY : src/cd_builtin.i

# target to preprocess a source file
src/cd_builtin.c.i:
	$(MAKE) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cd_builtin.c.i
.PHONY : src/cd_builtin.c.i

src/cd_builtin.s: src/cd_builtin.c.s

.PHONY : src/cd_builtin.s

# target to generate assembly for a file
src/cd_builtin.c.s:
	$(MAKE) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/cd_builtin.c.s
.PHONY : src/cd_builtin.c.s

src/env_builtin.o: src/env_builtin.c.o

.PHONY : src/env_builtin.o

# target to build an object file
src/env_builtin.c.o:
	$(MAKE) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/env_builtin.c.o
.PHONY : src/env_builtin.c.o

src/env_builtin.i: src/env_builtin.c.i

.PHONY : src/env_builtin.i

# target to preprocess a source file
src/env_builtin.c.i:
	$(MAKE) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/env_builtin.c.i
.PHONY : src/env_builtin.c.i

src/env_builtin.s: src/env_builtin.c.s

.PHONY : src/env_builtin.s

# target to generate assembly for a file
src/env_builtin.c.s:
	$(MAKE) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/env_builtin.c.s
.PHONY : src/env_builtin.c.s

src/ft_exe.o: src/ft_exe.c.o

.PHONY : src/ft_exe.o

# target to build an object file
src/ft_exe.c.o:
	$(MAKE) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/ft_exe.c.o
.PHONY : src/ft_exe.c.o

src/ft_exe.i: src/ft_exe.c.i

.PHONY : src/ft_exe.i

# target to preprocess a source file
src/ft_exe.c.i:
	$(MAKE) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/ft_exe.c.i
.PHONY : src/ft_exe.c.i

src/ft_exe.s: src/ft_exe.c.s

.PHONY : src/ft_exe.s

# target to generate assembly for a file
src/ft_exe.c.s:
	$(MAKE) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/ft_exe.c.s
.PHONY : src/ft_exe.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/minishell.dir/build.make CMakeFiles/minishell.dir/src/main.c.s
.PHONY : src/main.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... minishell"
	@echo "... edit_cache"
	@echo "... src/cd_builtin.o"
	@echo "... src/cd_builtin.i"
	@echo "... src/cd_builtin.s"
	@echo "... src/env_builtin.o"
	@echo "... src/env_builtin.i"
	@echo "... src/env_builtin.s"
	@echo "... src/ft_exe.o"
	@echo "... src/ft_exe.i"
	@echo "... src/ft_exe.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

